export const playerKeyLabelMapping = {
  'id': 'ID',
  'playerName': 'Player Name',
  'iplSeasonsPlayed': 'IPL Seasons Played',
  'role': 'Role',
  'totalRuns': 'Total Runs',
  'totalWickets': 'Total Wickets',
  'odiRunsS': 'ODI-RUNS-S',
  'odiSrB': 'ODI-SR-B',
  'odiWickets': 'ODI Wickets',
  'odiSrBL': 'ODI-SR-BL',
  'captaincyExp': 'Captaincy Experience',
  'runsS': 'RUNS-S',
  'hs': 'HS',
  'average': 'Average',
  'srB': 'SR-B',
  'sixers': 'Sixers',
  'runsC': 'RUNS-C',
  'wickets': 'Wickets',
  'aveBL': 'AVE-BL',
  'econ': 'ECON',
  'srBL': 'SR-BL',
  'basePrice': 'Base Price',
  'criticsRating': 'Critics Rating',
  'successAssestmentInPrecent': 'Success Assestment In Percent',
};

export const playerKeys = ['id',
'playerName',
'iplSeasonsPlayed',
'role',
'totalRuns',
'totalWickets',
'odiRunsS',
'odiSrB',
'odiWickets',
'odiSrBL',
'captaincyExp',
'runsS',
'hs',
'average',
'srB',
'sixers',
'runsC',
'wickets',
'aveBL',
'econ',
'srBL',
'basePrice',
'criticsRating',
'successAssestmentInPrecent',];

export const playerLabels = [ 'ID',
 'Player Name',
 'IPL Seasons Played',
 'Role',
 'Total Runs',
 'Total Wickets',
 'ODI-RUNS-S',
 'ODI-SR-B',
 'ODI Wickets',
 'ODI-SR-BL',
 'Captaincy Experience',
 'RUNS-S',
 'HS',
 'Average',
 'SR-B',
 'Sixers',
 'RUNS-C',
 'Wickets',
 'AVE-BL',
 'ECON',
 'SR-BL',
 'Base Price',
 'Critics Rating',
 'Success Assestment In Percent',];
